# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

version: '3'
services:
  geth-1990:
    build:
      context: .
    container_name: geth-1990
    ports:
      - "8545:8545"